apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bananas
  namespace: demo
spec:
  serviceName: bananas
  replicas: 2
  selector:
    matchLabels:
      app: bananas
  template:
    metadata:
      labels:
        app: bananas
    spec:
      containers:
      - name: bananas
        image: demo-service:latest
        imagePullPolicy: Never
        env:
        - name: SERVICE_NAME
          value: "bananas"
        - name: TARGETS
          value: "apples:8080"
        - name: INTERVALS
          value: "180"  # Call apples every 180s (3 minutes)
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bananas
  namespace: demo
spec:
  selector:
    app: bananas
  ports:
  - port: 8080
    targetPort: 8080
  clusterIP: None  # Headless service for StatefulSet
